### PR TITLE
Fix persons name bug

### LINKED ISSUE #117: Unable to Add Names with Slashes (e.g., "s/o") in the Contact Book
### **Description**
The application currently restricts the use of certain symbols in names, including the slash (`/`). This restriction prevents adding names that include "s/o," "d/o," etc., which are commonly used in legal names in some cultures. This limitation may inconvenience users who expect the application to support legally recognised name formats.

### **Steps to Reproduce**
1. Open the Address Book application.
2. Enter the following command to add a contact:
   ```
   add n/John s/o Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 w/Intern,Google,2024 u/NUS m/Biology t/friends t/owesMoney
   ```

### **Expected Behaviour**
The application should allow names containing slashes (`/`) since these are commonly used in legal name formats. The above input should be successfully added to the address book.

### **Actual Behaviour**
The application displays an error message: 
   ```
   Names should only contain alphanumeric characters and spaces, and it should not be blank
   ```
This prevents adding valid names with slashes, which can inconvenience users who need to store such names.

### **Suggested Solution**
Allow the use of slashes (`/`) in names by updating the input validation rules for names to permit this character. However, ensure that it does not conflict with command parsing (for example, by using the slash symbol as a prefix delimiter in commands).

### **Screenshots**
image

### PR DESCRIPTION
**Pull request by verakohh**
fix: allow slashes ("/") in names for cases like "s/o"
Fixes #117 

Updated validation logic in AddCommand to permit slashes in names, addressing the issue where entries with "s/o" or similar formats were previously rejected. This change improves compatibility with real-life naming conventions.

### CODE REVIEW

File: src/test/java/seedu/address/model/person/PersonTest.java [hunk 1]
```diff
@@ -72,44 +84,16 @@ public void equals() {
         // different type -> returns false
         assertFalse(ALICE.equals(5));
 
-        // different person -> returns false
-        assertFalse(ALICE.equals(BOB));
-
-        // different name -> returns false
-        Person editedAlice = new PersonBuilder(ALICE).withName(VALID_NAME_BOB).build();
-        assertFalse(ALICE.equals(editedAlice));
+        // different person with same phone -> returns true
```
Comment (arnav12344) [inline src/test/java/seedu/address/model/person/PersonTest.java:87]: Very informative and clear comment

**Review by arnav12344 — APPROVED** [review]
LGTM!
